# Generated by Django 3.2.10 on 2022-03-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='adress',
            field=models.CharField(max_length=200, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='category_fam',
            field=models.CharField(choices=[('полный', 'Полный'), ('неполный', 'Неполный')], default='Полный', max_length=10, verbose_name='Тип семьи'),
        ),
        migrations.AlterField(
            model_name='student',
            name='childs_in_family',
            field=models.CharField(blank=True, max_length=10, verbose_name='Количество детей'),
        ),
        migrations.AlterField(
            model_name='student',
            name='disability',
            field=models.CharField(choices=[('да', 'Да'), ('нет', 'Нет')], default='нет', max_length=20, verbose_name='Инвалидность'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_educ',
            field=models.CharField(blank=True, max_length=200, verbose_name='Образования'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО отца'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_org',
            field=models.CharField(blank=True, max_length=250, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_pos',
            field=models.CharField(blank=True, max_length=200, verbose_name='Позиция на работе'),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_tel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактные данные отца'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=250, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='student',
            name='kurator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.kurator', verbose_name='Выберите куратора'),
        ),
        migrations.AlterField(
            model_name='student',
            name='large_family',
            field=models.CharField(choices=[('да', 'ДА'), ('нет', 'НЕТ')], default='нет', max_length=10, verbose_name='Большая семья'),
        ),
        migrations.AlterField(
            model_name='student',
            name='learning_lang',
            field=models.CharField(choices=[('казахский', 'казахский'), ('русский', 'русский')], default='каазахский', max_length=10, verbose_name='Язык обучение'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_educ',
            field=models.CharField(blank=True, max_length=200, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО матери'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_org',
            field=models.CharField(blank=True, max_length=250, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_pos',
            field=models.CharField(blank=True, max_length=200, verbose_name='Позиция на работе'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_tel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактные данные матери'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_age',
            field=models.CharField(max_length=200, verbose_name='Возраст ученика'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_gender',
            field=models.CharField(choices=[('female', 'Женский'), ('male', 'Мужской')], default='none', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_nationality',
            field=models.CharField(max_length=100, verbose_name='Национальность'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_photo',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='student',
            name='stud_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.tutor', verbose_name='Выберите тьютора'),
        ),
        migrations.AlterField(
            model_name='student',
            name='vospitatel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.vospitatel', verbose_name='Выберите воспитателя'),
        ),
    ]
